import Colors from "@/constants/Colors";
import { Stack } from "expo-router";
import { StyleSheet } from "react-native";
import { text } from "./Styles";

export const styles = StyleSheet.create({
        contentContainer: {
          marginLeft: -10,
        },
        container: {
          flex: 1,
          padding: 20,
          backgroundColor: Colors.background,
          alignItems: "center",
          justifyContent: "center",
          gap:20,
        },
        header: {
        },
        body: {
          flex: 1,
          width: "auto",
          height: "auto",
          minWidth: 380,
          minHeight: 650,
          maxWidth: 380*3,
          maxHeight: 650*3,
          paddingVertical: 16,
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          alignSelf: 'center',
          marginBottom: 20, 
          flexShrink: 0,
      
        },
        subFrame: {
          display: 'flex',
          paddingVertical: 10,
          paddingHorizontal: 20,
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          alignSelf: 'stretch',
          gap:10,
        },
        RectangleShape: {
          minWidth: 300,
          minHeight: 70,
          width: "auto",
          height: "auto",
          alignItems: "center",
          justifyContent: "center",
          borderRadius: 12,
          flexDirection: "column",
          alignSelf: "stretch",
        },
        SmallRectangleShape: {
          minWidth:'auto',
          width: "auto",
          height: "auto",
          alignItems: "center",
          justifyContent: "center",
          borderRadius: 12,
          flexDirection: "column",
          alignSelf: 'stretch',
          paddingHorizontal:20,
        },
        vector: {
          minWidth: 250,
          width: "auto",
          height: 0,
          alignSelf: "stretch",
          borderWidth: 0.5,
          marginVertical: 5,
        },
        colorMainVector: {
          borderColor: Colors.gray,
        },
        colorVector: {
          borderColor: "#222831",
        },
        MainShape: {
          backgroundColor: Colors.primary,
          paddingHorizontal: 25,
          paddingVertical: 15,
        },
        WhiteShape: {
          backgroundColor: Colors.white,
          paddingHorizontal: 20,
          paddingVertical: 20,
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          gap: 5,
        },
        linkShape: {
          backgroundColor: Colors.white,
          marginVertical: 10,
        },
        memberShape: {
          display: 'flex',
          width: 'auto',
          paddingVertical: 'auto',
          paddingHorizontal:'auto',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: Colors.white,
          marginBottom: 'auto',
        },
        subTittle: {
          height: 18,
          alignSelf: "flex-start",
          color: '#00ADB5',
          fontSize: 16,
          fontStyle: 'normal',
          fontWeight: '700',
          lineHeight: 16 * 1.1,
        },
        aboveInfor: {
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          alignSelf: 'stretch', 
        },
        mainText: {
          color: '#222831',
          fontSize: 19,
          fontStyle: 'normal',
          fontWeight: '700',
          lineHeight: 16 * 1.4,
          alignSelf: "flex-start",
        },
        text: {
            color: '#222831',
            fontSize: 15,
            fontStyle: 'normal',
            fontWeight: '400',
            lineHeight: 14 * 1.4, // line height based on font size
            alignSelf: "flex-start",
            width: "auto",
        },
        subItem: {
          display: "flex",
          minWidth: 270,
          width: 'auto',
          height: 'auto',
          alignItems: "center",
          flexDirection: "row",
          justifyContent: "center",
          alignSelf: 'stretch', 
          gap: 12,
        },
        itemText: {
          alignItems: 'center',
          justifyContent: 'space-between',
          fontSize: 15,
          fontStyle: 'normal',
          fontWeight: '400',
          lineHeight: 12 * 1.4, // line height based on font size
        },
        smallIcon: {
          width: 15,
        height: 15,
        },
        MediumIcon: {
          width: 23,
          height: 23,
        },
        itemComponnent: {
          display: "flex",
          width: "auto",
          alignItems: "center",
          alignSelf: 'center',
          gap: 6,
          flexDirection: "row",
        },
        InforMember: {
          display: 'flex',
          minWidth: 150,
          width: 'auto',
          paddingVertical: 'auto',
          paddingHorizontal: 'auto',
          flexDirection: 'column',
          alignItems: 'flex-start',
          marginVertical: 10,
          flex: 1,
        },
        titleDescription: {
          fontSize: 17,
          fontStyle: 'normal',
          fontWeight: '900',
          lineHeight: 13 * 1.4,
        },
        contentDescription: {
          width: 'auto',
          height: 'auto',
          alignSelf: "stretch",
          flexShrink: 0,
          color: '#4E4E4E',
          textAlign: 'center',
          fontSize: 15,
          fontStyle: 'normal',
          fontWeight: '400',
          lineHeight: 13 * 1.4,
        },
        destinationText: {
          color: '#0048B5',
          textAlign: 'center',
         fontSize: 20,
         fontStyle: 'normal',
         fontWeight: '600',
         lineHeight: 24, // Height of the text line, adjust as needed
      },
      miniText: {
        color: Colors.gray,
        fontSize: 14,
        fontWeight: "400",
      },
      textPrimary: {
        ...text.normalNoPadding,
        fontSize: 20,
        fontWeight: "700",
        lineHeight: 22,
        color: Colors.primary,
      },
      userInfoContainer: {
        flex: 0,
        padding: 20,
        flexDirection: "column",
        backgroundColor: Colors.primary,
        gap: 16,
        borderRadius: 12,
        alignSelf: "stretch", // fill-container
      },
      infoContainer: {
        flex: 0,
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        flexDirection: "row",
        gap: 12,
      },
      avatar: {
        flexShrink: 0,
        width: 30,
        height: 30,
      },
      namePosition: {
        flex: 0,
        alignItems: "flex-start",
        gap: 8,
      },
      icon: {
        flex: 1,
        alignItems: "flex-end",
      },
      projectContainer: {
        flex: 0,
        alignItems: "flex-start",
        gap: 12,
        alignSelf: "stretch",
        flexDirection: "row",
      },
      divideContainer: {
        flex: 1,
        alignItems: "center",
        gap: 8,
        flexDirection: "row",
      },
})